---
- name: update apt package index
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: restart docker service
  service:
    name: docker
    state: restarted
