---
- name: initialize swarm cluster
  shell: >
    docker swarm init
    --advertise-addr={{ swarm_iface | default('eth1') }}:2377
  with_items: "{{ groups['swarm_manager_bootstrap[0]'] }}"
  when:
    - "'swarm_manager_operational' not in groups"
  register: bootstrap_first_node
  run_once: true

- name: add initialized host to swarm_manager_operational group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_operational
  with_items: "{{ groups['swarm_manager_bootstrap[0]'] }}"
  when:
    - bootstrap_first_node is changed
  run_once: true
