---
- name: retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token
  with_items: "{{ play_hosts }}"
  when: inventory_hostname in groups['swarm_manager_operational']

- name: retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
  when: inventory_hostname in groups['swarm_manager_operational']

- name: populate list of manager ips
  add_host:
    hostname: "{{ hostvars[item]['ansible_' + iface]['ipv4']['address'] }}"
    groups: swarm_manager_ips
  with_items: "{{ play_hosts }}"
  when: item in groups['swarm_manager_operational']
