---
- hosts: workers
  become: true
  tasks:
    - name: load docker info as facts (determine swarm status)
      docker_info_facts:

    - name: create swarm_worker_operational group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_worker_operational
      with_items: "{{ play_hosts }}"
      when: hostvars[item]['docker_info']['Swarm']['LocalNodeState'] == 'active'
      run_once: true

    - name: create swarm_worker_bootstrap group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_worker_bootstrap
      with_items: "{{ play_hosts }}"
      when: hostvars[item]['docker_info']['Swarm']['LocalNodeState'] != 'active'
      run_once: true
